name: Build and deploy .NET Core application to Web App tms-be-api
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: tms-be-api
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: ./TMS-BE
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}/TMS-BE.sln"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}/TMS-BE.sln" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}/TMS-BE.sln" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}/API.csproj" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Debug publish output
      shell: bash
      run: |
        echo "ðŸ“¦ Checking publish directory:"
        ls -R ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Zip published output
      shell: pwsh
      run: |
        Write-Host "Zipping publish folder..."
        Compress-Archive -Path "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}\*" -DestinationPath "app.zip"

    - name: Check zip contents
      shell: pwsh
      run: |
        Write-Host "Contents of app.zip:"
        Expand-Archive -Path "app.zip" -DestinationPath "unzipped" -Force
        Get-ChildItem -Recurse "unzipped"

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.TMS_BE_API_SPN }}

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./app.zip

